language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"

# install dependencies
install:
  - pip install nose
  - pip install numpy
  - pip install scipy
  - pip install traits
  - pip install traitsui
  - pip install pyface
# run tests
script:
  - nosetests
